use_frameworks!

target 'DecodeFailable_Example' do
  pod 'DecodeFailable', :path => '../'

  target 'DecodeFailable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end
